In [52]:
import pandas as pd

In [53]:
listings = pd.read_csv("CRMLSListing202602.csv")

In [54]:
listings.head()

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,655000.0,1156756810,NaN,NaN,Katherine,Materiale,33.558513,-117.222967,24395 Silver Bullet Way,Residential,...,4.0,False,3.0,Murrieta,92562,NaN,0.0,7841.0,NaN,24395 Silver Bullet Way
1,2199999.0,1156755185,NaN,NaN,Laurie,Vallett,33.070451,-117.236133,3311 Camino Coronado,Residential,...,1.0,False,2.0,San Dieguito Union,92009,NaN,145.0,6300.0,NaN,3311 Camino Coronado
2,499000.0,1156731071,NaN,NaN,Joanna,Freter,32.801784,-117.236897,1855 Diamond St 5-218,Residential,...,NaN,NaN,1.0,San Diego Unified,92109,NaN,808.0,NaN,NaN,1855 Diamond St 5-218
3,1990000.0,1156727152,NaN,NaN,Yueming,Zhang,33.668432,-117.716317,446 Chorus,Residential,...,3.0,False,2.0,Irvine Unified,92618,NaN,240.0,4990.0,NaN,446 Chorus
4,1459000.0,1156723304,NaN,NaN,Missy,Sandefur,33.585150,-117.651884,27301 Monforte,Residential,...,0.0,False,2.0,Capistrano Unified,92692,NaN,350.0,5040.0,NaN,27301 Monforte

In [55]:
listings.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,Latitude.1,ListPrice.1,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,3.162200e+04,3.175500e+04,9.089000e+03,31295.000000,31307.000000,27462.000000,3.166500e+04,31755.000000,0.0,0.0,...,31295.000000,3.166500e+04,0.0,23580.000000,2.908700e+04,14906.000000,25373.000000,22178.000000,2.904400e+04,0.0
mean,1.116404e+06,1.153119e+09,8.142967e+05,34.552338,-118.411538,1937.861536,1.026128e+06,20.300803,NaN,NaN,...,34.552338,1.026128e+06,NaN,1.364716,8.171159e+04,1.925332,1.730225,221.002354,3.626636e+05,NaN
std,7.221255e+06,8.835311e+05,1.150676e+06,1.646065,3.453059,1622.152499,2.184104e+06,18.246873,NaN,NaN,...,1.646065,2.184104e+06,NaN,0.481361,2.949256e+06,1.507310,2.854804,463.726403,1.534652e+07,NaN
min,1.000000e+00,1.063377e+09,1.770000e+00,0.000000,-124.198589,0.000000,1.000000e+00,-10.000000,NaN,NaN,...,0.000000,1.000000e+00,NaN,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,NaN
25%,1.349990e+05,1.152615e+09,4.850000e+03,33.757961,-118.542337,1176.000000,1.349950e+05,6.000000,NaN,NaN,...,33.757961,1.349950e+05,NaN,1.000000,4.985500e+03,1.000000,1.000000,0.000000,5.300000e+03,NaN
50%,6.490000e+05,1.153094e+09,6.150000e+05,34.054426,-118.099697,1605.000000,6.490000e+05,17.000000,NaN,NaN,...,34.054426,6.490000e+05,NaN,1.000000,7.389000e+03,2.000000,2.000000,0.000000,7.630500e+03,NaN
75%,1.195000e+06,1.153441e+09,1.150000e+06,34.420678,-117.290296,2264.000000,1.181180e+06,33.000000,NaN,NaN,...,34.420678,1.181180e+06,NaN,2.000000,1.500000e+04,3.000000,2.000000,350.000000,1.840700e+04,NaN
max,8.195000e+08,1.156757e+09,3.026000e+07,41.891615,118.084350,94619.000000,9.135000e+07,710.000000,NaN,NaN,...,41.891615,9.135000e+07,NaN,2.000000,4.187423e+08,32.000000,400.000000,14220.000000,1.897866e+09,NaN

In [56]:
listings.columns

Index(['OriginalListPrice', 'ListingKey', 'CloseDate', 'ClosePrice',
       'ListAgentFirstName', 'ListAgentLastName', 'Latitude', 'Longitude',
       'UnparsedAddress', 'PropertyType', 'LivingArea', 'ListPrice',
       'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'PropertyType.1', 'MlsStatus', 'ElementarySchool',
       'ListAgentFirstName.1', 'AttachedGarageYN', 'ParkingTotal',
       'BuilderName', 'PropertySubType', 'LotSizeAcres', 'SubdivisionName',
       'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1', 'StreetNumberNumeric',
       'LivingArea.1', 'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'Longitude.1', 'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'Latitude.1', 'ListPrice.1', 'StateOrProvince',
       'CoveredSpaces', 'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories',
       'HighSchool', 'Levels', 'ListAgentLastName.1', 'CloseDate.1',
       'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1'],
      dtype='object')